version: "3"
services:
  nginx:
    image: nginx:1.21
    network_mode: host
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always